apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-api
  labels:
    app: sql
spec:
  selector:
    matchLabels:
      app: sql
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sql
    spec:
      containers:
        - name: mysql
          image: datascientest/mysql-k8s:1.0.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              # value: datascientest1234
              valueFrom:
                secretKeyRef:
                  name: sql-api
                  key: password
            - name: MYSQL_DATABASE
              value: Main
        - name: fastapi
          image: akinasorrow/fastapi:1.0.6
          ports:
            - containerPort: 8000
          env:
            - name: password
              # value: datascientest1234
              valueFrom:
                secretKeyRef:
                  name: sql-api
                  key: password
            - name: user
              value: root